<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/upload.proto

namespace Upload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>upload.UploadResponse</code>
 */
class UploadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string savePath = 1;</code>
     */
    protected $savePath = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $savePath
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Upload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string savePath = 1;</code>
     * @return string
     */
    public function getSavePath()
    {
        return $this->savePath;
    }

    /**
     * Generated from protobuf field <code>string savePath = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSavePath($var)
    {
        GPBUtil::checkString($var, True);
        $this->savePath = $var;

        return $this;
    }

}

