<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/upload.proto

namespace Upload;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>upload.UploadRequest</code>
 */
class UploadRequest extends \Google\Protobuf\Internal\Message
{
    protected $Data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $file
     *     @type \Upload\FileInfo $fileInfo
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Upload::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes file = 1;</code>
     * @return string
     */
    public function getFile()
    {
        return $this->readOneof(1);
    }

    public function hasFile()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>bytes file = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFile($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.upload.FileInfo fileInfo = 2;</code>
     * @return \Upload\FileInfo|null
     */
    public function getFileInfo()
    {
        return $this->readOneof(2);
    }

    public function hasFileInfo()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.upload.FileInfo fileInfo = 2;</code>
     * @param \Upload\FileInfo $var
     * @return $this
     */
    public function setFileInfo($var)
    {
        GPBUtil::checkMessage($var, \Upload\FileInfo::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getData()
    {
        return $this->whichOneof("Data");
    }

}

